version: '3.8'

services:
  translate:
    image: libretranslate/libretranslate:latest
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 3G
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
