version: '3.8'

services:
  translate:
    image: libre/translate:v1.0.0
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 3G
    ports:
      - "5000"

  nginx:
    image: libre/nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
