version: '3.8'

services:
  translate:
    image: libre/translate:v1.0.0
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 3G
    ports:
      - "5000:5000"
    entrypoint: ["./venv/bin/libretranslate", "--host", "*", "--threads", "16"]
    environment:
      - LT_THREADS=16
    logging:
      options:
        max-size: "10m"
        max-file: "3"
