version: '3.8'

services:
  translate:
    image: libre/translate:v1.0.0
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 3G
    ports:
      - "5000"
    environment:
      - LT_THREADS=8
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: libre/nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          memory: 200M
    logging:
      options:
        max-size: "10m"
        max-file: "3"
