version: "3"

services:
  libretranslate-cuda:
    image: libre/translate-cuda:v1.0.0
    build:
      context: .
      dockerfile: docker/cuda.Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    logging:
      options:
        max-size: "10m"
        max-file: "3"

